version: "3.1"

services:
  unilingo-api:
    container_name: unilingo_api_${APP_ENV:?error}
    restart: always
    build:
      context: ./unilingo
    ports:
      - ${API_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENV}
      - ConnectionStrings:DefaultConnection=${APP_DB_STRING}
      - Environment=${APP_ENV}
      - YouTubeAPI:ApiKey=${APP_YT_KEY}
  unilingo-ui:
    container_name: unilingo_angular_ui_${APP_ENV:?error}
    restart: always
    build:
      context: ./unilingo-frontend
    ports:
      - ${UI_PORT}:80
    environment:
      - UI_API_BASE_URL=${UI_API_BASE_URL} 