// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using unilingo.ContextDB;

#nullable disable

namespace unilingo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231115203043_AddViewCount")]
    partial class AddViewCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("unilingo.Model.VideoInformation", b =>
                {
                    b.Property<string>("IdVideo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdVideo");

                    b.ToTable("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
